# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - shop-dev-dh

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm ci
          npx prisma generate
          npm run build --if-present
          npm run test --if-present

      - name: Prepare artifact for deployment
        run: |
          mkdir deploy-folder
          cp -R * deploy-folder/
          cp -R .next deploy-folder/.next || true
          cp -R prisma deploy-folder/prisma || true
          cp -R node_modules/.prisma deploy-folder/node_modules/.prisma || true
          cp -R node_modules/@prisma deploy-folder/node_modules/@prisma || true
          zip -r release.zip deploy-folder

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4B9252F2CA1844C8BBF5BE9B3D640F49 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_76861A33795547BAB4AA21945C7C818A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_95F45E4D63AE42D197847FC14B6C6FC9 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'shop-dev-dh'
          slot-name: 'Production'
          package: deploy-folder
